# This workflow will build a Java project with Maven
# For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
# https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
# https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven
# https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven#publishing-packages-to-github-packages
# https://docs.github.com/en/actions/security-guides/automatic-token-authentication

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Share data with another job in the same workflow
        run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v2
#        with:
#          name: package
#          path: staging
  publish:
    if: (github.event_name == 'push' && contains(github.ref, 'main')) || github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Download
        uses: actions/download-artifact@v2
#        with:
#          name: package
#          path: staging
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
